# Generated by Django 4.2.7 on 2023-12-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0003_twit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
    ]
