# Generated by Django 4.2.7 on 2023-12-12 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Social', '0004_userprofile_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='twit_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
