# Generated by Django 4.2.7 on 2023-12-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0006_userprofile_bio_userprofile_github_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=999999999, null=True),
        ),
    ]
